### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by chriship** [elliotwoods/ofxOrbbec#2]
Hi,

I've tried both the example (from within the addons/ofxOrbbec folder) and adding ofxOrbbec with the project generator but am having trouble compiling with both of these.

Are there any setup instructions? Do I need to add ofxOrbbecLib as a project into the solution (note I've tried this and am getting an error where VS is unable to read the project)?

I'm using OF 0.9.8 and VS.

Thanks!

**Comment by elliotwoods** [comment]
hey!
do the examples build for you?

**Comment by chriship** [comment]
They don't but I think it's because I don't have libskeleton. Is that required even if only depth or RGB is used?

**Comment by elliotwoods** [comment]
aha!
yes will need to remove every mention of Skeleton from the addon if you want to work without libskeleton

Mostly that means:
* removing/commenting out lines from Device.cpp and Device.h referring to skeleton
* remove Skeleton.cpp and Skeleton.h from the project
* remove any includes to Skeleton.h

**Comment by chriship** [comment]
Great, thanks Elliot!

**Comment by Joachim-oYo** [comment]
Hi @elliotwoods , is there any way that we can get libskeleton? I have the new Astra SDK with body tracking, and it works with their samples, but I'd really like to use the tools you've created so that I can perform skeleton tracking inside of an openframeworks app I'm developing. Would the proper library be under a different name in the Astra SDK? Thanks so much!

**Comment by elliotwoods** [comment]
@joshblake - could you help @Joachim-oYo 's request?
What's the latest regarding libskeleton?
Still not for open release?

I presume that if there have been many updates since, that the API has changed also

thank you
elliot

**Comment by JoshBlake** [comment]
@elliotwoods @Joachim-oYo libskeleton has been integrated into Astra SDK. The a few versions of the integrated releases have been published on https://orbbec3d.com/develop since around Fall 2017. :) The API is different, yes, so any openframeworks projects should update to use Astra SDK.

**Comment by mattfelsen** [comment]
@Joachim-oYo I haven't been keeping up, but I wrote another OF addon a while ago that somebody has forked and it looks like has added body tracking support to. I haven't tested it, but you could give it a shot: https://github.com/pierrep/ofxOrbbecAstra

**Comment by Joachim-oYo** [comment]
Awesome, thank you, everyone! I ended up getting things working with ofxOrbbecAstra! Separately, if I want to access the depth pixels (either raw or from the depth image) so that I can perform blob tracking on my image (my idea is to perform blob tracking and then basically, turn a blob into a certain color if it contains enough tracked joints inside of its bounding box), how would I best go about doing that? 

Right now, I'm getting a float from astra.getRawDepth().getColor(x_pos, y_pos).getBrightness() in order to determine which pixels correspond to which depth values. From the values I'm getting, it seems like low brightness values actually correspond to points that are closer to the camera, and high brightness values correspond to points that are further away. Am I interpreting the raw depth correctly; also, am I losing any fidelity this way? My main purpose for using raw depth instead of the depth image pixels was just for more precision in tracking when deciding what to threshold out for my body detection.

Thanks a lot!

**Comment by mattfelsen** [comment]
That sounds correct - the value is that pixel's distance from the camera in mm, which is typically how most depth cameras report depth values. You're not losing any fidelity - that is the correct way to access that raw depth values before they get rescaled into a 0-255 range based on your near/far plane settings.
